### PR TITLE
OCPBUGS-32869: replaces deprecated square/go-jose wtih go-jose/go-jose

### PR DESCRIPTION
**Pull request by apoorvajagtap**
This commit replaces all the references of [github.com/square/go-jose](https://github.com/square/go-jose) to [github.com/go-jose/go-jose@v2](https://github.com/go-jose/go-jose).

Manual cherry-pick of #333

### CODE REVIEW

**Review by ramessesii2 — APPROVED** [review]
/lgtm

**Comment by apoorvajagtap** [comment]
/assign @adambkaplan @sayan-biswas 
for approval

**Review by sayan-biswas — APPROVED** [review]

**Pull request merged**
