### PR TITLE
template namespace processing

### PR DESCRIPTION
**Pull request by sanchezl**
* Bump library-go to pick up fixes for template processing.
* handle template without namespace.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by flavianmissi** [comment]
retest-required

**Comment by sanchezl** [comment]
` [sig-arch] events should not repeat pathologically` should be fixed by https://github.com/openshift/origin/pull/27474.
It has already merged, not sure when CI will pick it up.

**Pull request merged**
