### PR TITLE
remove use of BUILD_ISOLATION env var (no longer inspected in openshift/builder)

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick of #161 required

/assign @adambkaplan 
/assign @jupierce 
/assign @crawford 

required https://github.com/openshift/builder/pull/208 has merged

@bparees @nalind FYI

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by crawford** [comment]
Tests didn't get scheduled...

/retest

**Comment by gabemontero** [comment]
CI fails 

/retest

**Pull request merged**
