### PR TITLE
Revert Revert OCPBUGS-36833: 4.16 "Bad" reconciliation loops can cause unbounded dockercfg secret creation

### PR DESCRIPTION
**Pull request by sanchezl**
Reapplying #319 with fix for nil pointer dereference panic

### CODE REVIEW

**Comment by soltysh** [comment]
/hold
since we're thinking about merging the revert https://github.com/openshift/openshift-controller-manager/pull/321

**Comment by sanchezl** [comment]
/payload periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by sanchezl** [comment]
/hold cancel 
payload jobs completed successfully

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by pgodowski** [comment]
@sanchezl if I correctly understand the PR, it will address the issue where the image pull Secrets were generated in the massive scale, at the same time pruning the previously created image pull Secrets which are now orphaned. Good.

But seems this PR does not resolve the scenario where there is 3rd party controller creating / managing ServiceAccount and where the annotation `InternalRegistryAuthTokenServiceAccountAnnotation` is removed by the 3rd party controller and then re-added by OCP SA controller, right? Meaning, that there will be still some form of "race condition"  between two controllers, but at least there will be no side effect of it, resulting with thousands of Secrets created?

If so, what is the plan / issue to resolve that "race condition" scenario? The net results is that 3rd party controllers will start spinning around, together with OCP, consuming compute resources without any good reason.

I think that the proper fix is that the SA controller should create the image pull secret and then annotate such Secret with the reference to its SA, rather than annotate SA to point to the Secret.

**Pull request merged**
