### PR TITLE
Bug 1767047: add leader lock for cluster-policy-controller in scc_namespace_allocator controller

### PR DESCRIPTION
**Pull request by sallyom**
pick of e5eae1cec1da32a1bfed10eb35e1560ed20bd06d

requires this: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/300

/cc @soltysh

### CODE REVIEW

**Comment by deads2k** [comment]
@sallyom link the 4.2 rbac PR in the operator

**Comment by sallyom** [comment]
> @sallyom link the 4.2 rbac PR in the operator

and needs a hold til this merges: https://github.com/openshift/openshift-controller-manager/pull/37?  

/hold

**Comment by derekwaynecarr** [comment]
the requisite pr is tagged for merge, do they both need to merge in order to ship?

**Comment by sallyom** [comment]
> the requisite pr is tagged for merge, do they both need to merge in order to ship?

Yes, retesting and unhold - this is required for upgrades 4.2-4.3 so the NewNamespaceSCCAllocationController in openshift-controller-manager (4.2) doesn't interfere w/ NewNamespaceSCCAllocationController in cluster-policy-controller (4.3 -it moved).

**Comment by sallyom** [comment]
@soltysh i see this failure: `StdErr: "Error from server (NotFound): imagestreams.image.openshift.io \"ruby-22-centos7\" not found",`  you fixed that in master unit tests, right? so it's failing in 4.2 also? :eyes:

**Comment by soltysh** [comment]
> @soltysh i see this failure: `StdErr: "Error from server (NotFound): imagestreams.image.openshift.io \"ruby-22-centos7\" not found",` you fixed that in master unit tests, right? so it's failing in 4.2 also? eyes
> 
> ah, maybe it needs this to merge: [openshift/origin#24109](https://github.com/openshift/origin/pull/24109)

We also need to cherry-pick https://github.com/openshift/oc/pull/152 to origin, on it...

**Comment by sallyom** [comment]
https://github.com/openshift/origin/pull/24109  will fix `e2e-aws-builds`

**Comment by mfojtik** [comment]
/test all

lets give this one more round of green tests.

**Comment by mfojtik** [comment]
Seems all green, approving.

**Pull request merged**
