### PR TITLE
OCPBUGS-33815: openshift-controller-manager overwriting/undoing changes to ServiceAccount imagePullSecrets

### PR DESCRIPTION
**Pull request by sanchezl**
The ServiceAccount.ImagePullSecrets field does not have a merge strategy defined. As such, when using (server-side) Apply to update the ImagePullSecrets field, we have to be careful to not clobber the contents added by other clients. This is in contrast to the ServiceAccounts.Secret field, where ownership is at the level of an individual entry in the list.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by sjenning** [comment]
hypershift is experiencing a CI outage

/override ci/prow/e2e-hypershift-conformance

**Pull request merged**
