### PR TITLE
Bug 1813361: fix img reg ref on ICT if OCM knows img reg host before apiserver

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @dmage 

@openshift/openshift-team-developer-experience FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
/test e2e-aws-builds

This has some ICT based invocations (image-eco is not set up on this repo)

**Comment by gabemontero** [comment]
/assign @bparees 

didn't quite fix our old `OCM already knows about the registry name, but the API server hasn't seen it yet` friend back in December wrt ICTs

**Comment by bparees** [comment]
"whoops"

/lgtm

**Pull request merged**
