### PR TITLE
remove use of BUILD_ISOLATION env var (no longer inspected in openshift/builder)

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick of https://github.com/openshift/openshift-controller-manager/pull/160 required

tests won't pass until https://github.com/openshift/builder/pull/207 merges

/assign @bparees 

@adambkaplan @jupierce FYI

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

Until https://github.com/openshift/builder/pull/207 merges

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by crawford** [comment]
openshift/builder#207 has merged

/hold cancel

**Comment by gabemontero** [comment]
the tests passed with e2e-aws-builds but the release lease failed:

```
error: some steps failed:
  * could not run steps: step e2e-aws-builds failed: status 500 Internal Server Error, statusCode 500 releasing us-west-1--14
time="2021-01-21T22:57:53Z" level=info msg="Reporting job state 'failed' with reason 'executing_graph:step_failed:utilizing_lease:releasing_lease'"
```

/retest

**Comment by gabemontero** [comment]
Problem pulling from CI registry e2e-aws-builds 

/test e2e-aws-builds

**Pull request merged**
