### PR TITLE
Bug 1947793: Deprecated API in use

### PR DESCRIPTION
**Pull request by coreydaley**
bump openshift/api
bump(*)

### CODE REVIEW

**Comment by wewang58** [comment]
Launched a cluster with cluster-bot, no DeprecatedAPIInUse info alerts display now.
/lgtm

**Review by adambkaplan — APPROVED** [review]
/approve

I believe openshift/cluster-config-operator#192 actually merged the CRD type change in. That said, we do need to bump k8s to v1.21 anyway.

**Pull request merged**
