### PR TITLE
TRT-1632: Revert #298 "OCPBUGS-32729: Rollback state of managed image pull secrets after downgrade."

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts #298 ; tracked by [TRT-1632](https://issues.redhat.com//browse/TRT-1632)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Appears to have caused a rare but noticable number of pod panics that are affecting payloads.

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-upgrade 10
```

This is not a guaranteed reproducer as the actual fail rate seems pretty low, but it's at least some confirmation.

CC: @sanchezl

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by dgoodwin** [comment]
/override ci/prow/e2e-gcp-ovn-builds
/override ci/prow/e2e-aws-ovn-proxy
/override ci/prow/e2e-aws-ovn
/override ci/prow/e2e-gcp-ovn
/override ci/prow/e2e-aws-ovn-upgrade
/override ci/prow/security
/override ci/prow/openshift-e2e-aws-ovn-builds-techpreview

Going back to known good state, overriding jobs per policy.

**Review by sanchezl — APPROVED** [review]
/lgtm

**Comment by sanchezl** [comment]
The fix PR is out there: https://github.com/openshift/openshift-controller-manager/pull/300

**Comment by dgoodwin** [comment]
/override ci/prow/e2e-gcp-ovn-builds 

This is failing everywhere

**Pull request merged**
